let piropos = [
"Si la belleza fuera delito, tú tendrías cadena perpetua.",
"Eres la razón por la que sonrío al ver mi celular.",
"¿Eres maga? Porque cuando apareces, todo lo demás desaparece.",
"Contigo, hasta los lunes se sienten como viernes.",
"Tienes una sonrisa que ilumina más que el sol de Ica.",
"Si fueras canción, serías mi favorita en repeat.",
"Eres como el café: me despiertas solo con verte.",
"¿Tienes mapa? Porque me perdí en tu mirada.",
"Eres la casualidad más bonita que me ha pasado.",
"Tu risa debería estar patentada de lo contagiosa que es.",
"Eres arte, y yo solo quiero admirarte.",
"Si la perfección existiera, tendría tu nombre.",
"Caminas y hasta el viento se pone celoso.",
"Eres el mensaje que siempre quiero recibir.",
"Tu presencia convierte un día normal en extraordinario.",
"Eres como las estrellas: aunque lejos, brillas.",
"¿Eres poesía? Porque rimas con todo lo hermoso.",
"Me gustas más que la lasaña de Garfield un domingo.",
"Eres el WiFi de mi corazón, siento conexión contigo.",
"Si fueras postre, serías el más dulce.",
"Tienes un encanto que ni el tiempo puede borrar.",
"Eres mi notificación favorita.",
"Tu mirada tiene más brillo que mil diamantes.",
"Eres la melodía que no sale de mi cabeza.",
"¿Eres sol? Porque iluminas mi día.",
"Contigo todo es mejor, hasta el silencio.",
"Eres tan genial que hasta Siri te envidia.",
"Tu bondad es tan grande como tu belleza.",
"Si fueras libro, serías best seller.",
"Eres el arcoíris después de mi tormenta.",
"Tienes un corazón tan bonito como tu cara.",
"Eres mi lugar favorito a donde ir.",
"¿Eres chef? Porque has cocinado mi corazón.",
"Tu voz es mi sonido favorito.",
"Eres más dulce que el helado en verano.",
"Si la simpatía fuera oro, serías millonaria/o.",
"Eres la estrella de mi película favorita.",
"Tu alegría es contagiosa, no dejes de reír.",
"Eres como un buen meme: siempre me alegras.",
"¿Eres luna? Porque en mis noches oscuras brillas.",
"Eres la prueba de que los ángeles existen.",
"Tu forma de ser enamora más que tu físico.",
"Eres increíble, no cambies nunca.",
"Si fueras flor, serías la más hermosa del jardín.",
"Tienes magia, haces que todo sea especial.",
"Eres mi pensamiento favorito del día.",
"Tu energía positiva se siente a kilómetros.",
"Eres como el chocolate: imposible no quererte.",
"¿Eres tesoro? Porque vales oro.",
"Tu sonrisa arregla hasta el peor día.",
"Eres la definición de perfección.",
"Me encanta tu forma de ver la vida.",
"Eres luz en medio de la oscuridad.",
"Si fueras estrella, serías la más brillante.",
"Tienes un alma tan bella como tú.",
"Eres el mejor plan sin planearlo.",
"Tu risa es música para mis oídos.",
"Eres tan única/o como un copo de nieve.",
"¿Eres imán? Porque me atraes sin querer.",
"Eres mi casualidad favorita.",
"Tu presencia es un regalo.",
"Eres más refrescante que la chicha morada helada.",
"Si fueras sueño, no querría despertar.",
"Eres la chispa que enciende mi día.",
"Tu amabilidad es tu superpoder.",
"Eres como un abrazo: das calor.",
"¿Eres pintura? Porque eres una obra de arte.",
"Eres la mejor parte de mi día.",
"Tu inteligencia brilla tanto como tú.",
"Eres un 10, pero en mi corazón eres un 100.",
"Si fueras tiempo, querría que te detuvieras.",
"Eres tan linda/o que hasta los espejos sonríen.",
"Tu forma de hablar enamora.",
"Eres mi inspiración diaria.",
"¿Eres jardín? Porque floreces donde estás.",
"Eres la calma en mi caos.",
"Tu mirada dice más que mil palabras.",
"Eres como el mar: inmensa/o y hermosa/o.",
"Si fueras nota musical, serías la más alta.",
"Eres el plot twist bonito de mi historia.",
"Tu sinceridad es admirable.",
"Eres tan cool que ni el hielo te iguala.",
"¿Eres fuego? Porque enciendes mi corazón.",
"Eres la respuesta a mis oraciones.",
"Tu compañía es mi lugar seguro.",
"Eres más valiosa/o que un tesoro pirata.",
"Si fueras color, serías el más vivo.",
"Eres la melodía perfecta.",
"Tu dulzura no tiene comparación.",
"Eres como el amanecer: hermosa/o y esperanzadora/or.",
"¿Eres libro? Porque quiero leerte toda la vida.",
"Eres mi emoji favorito en persona.",
"Tu humildad te hace aún más grande.",
"Eres la cereza del pastel.",
"Si fueras viaje, serías mi destino favorito.",
"Eres tan especial que no hay palabras.",
"Tu forma de reír es mi debilidad.",
"Eres luz, amor y alegría juntos.",
"¿Eres estrella fugaz? Porque al verte pido un deseo: conocerte más.",
"Eres simplemente espectacular.",
"Tu corazón es de oro puro.",
"Eres mi buena suerte.",
"Si fueras canción de reggaetón, serías el perreo perfecto... de amor bonito.",
"Eres la mejor historia para contar.",
"Tu belleza es natural, sin filtros.",
"Eres como el cielo de Ica: despejado y hermoso.",
"Eres mi motivación para ser mejor.",
"¿Eres café pasado? Porque me tienes despierto pensando en ti. (versión peruana)",
"Eres única/o, no hay copia.",
"Tu sonrisa vale más que mil piropos."
];

let handler = async (m, { conn, text, usedPrefix, command }) => {
  let who = m.mentionedJid && m.mentionedJid[0]? m.mentionedJid[0] : m.sender;
  let name = who === m.sender? 'para ti' : '@' + who.split('@')[0];

  let piropo = piropos[Math.floor(Math.random() * piropos.length)];

  let txt = `💘 *PIROPO* 💘\n\n${name}, ${piropo}\n\n> _Usa ${usedPrefix + command} @user para dedicar otro_`;

  await conn.sendMessage(m.chat, { text: txt, mentions: [who] }, { quoted: m });
}

handler.help = ['piropo @user'];
handler.tags = ['fun'];
handler.command = ['piropo', 'piropos'];

export default handler;