let piropos = [
"Si la belleza fuera tiempo, tú serías la eternidad.",
"Eres la calma que mi corazón siempre buscó.",
"Amarte fue un accidente hermoso del destino.",
"Tu mirada es el lugar donde quiero perderme siempre.",
"Eres mi poema favorito sin haber escrito una palabra.",
"Si el amor tuviera rostro, tendría el tuyo.",
"Contigo entendí que el hogar no es un lugar, es una persona.",
"Eres la melodía más dulce que ha escuchado mi alma.",
"Tu sonrisa es la cura para todos mis días grises.",
"Te pienso y el mundo se vuelve más bonito.",
"Eres el sueño que no quiero dejar de soñar.",
"Mi corazón late más fuerte cuando estás cerca.",
"Eres la historia de amor que siempre quise vivir.",
"Tu amor es mi refugio en la tormenta.",
"Cada latido mío susurra tu nombre.",
"Eres la luz que guía mis noches oscuras.",
"Si tuviera que elegir de nuevo, te elegiría a ti mil veces.",
"Tu presencia convierte lo ordinario en extraordinario.",
"Eres mi principio y quiero que seas mi final.",
"Amarte es lo más natural que he hecho.",
"Tu voz es mi canción favorita.",
"Eres el abrazo que mi alma necesitaba.",
"En tus ojos encontré mi universo entero.",
"Eres la razón de mis suspiros.",
"Tu amor me hace querer ser mejor persona.",
"Eres mi destino escrito en las estrellas.",
"Contigo, el tiempo se detiene y todo tiene sentido.",
"Eres la ternura hecha persona.",
"Mi amor por ti crece con cada amanecer.",
"Eres el regalo más hermoso que me dio la vida.",
"Tu risa es la banda sonora de mi felicidad.",
"Eres mi paz en medio del caos.",
"Si el cielo existe, debe parecerse a estar contigo.",
"Tu mano encaja perfecto en la mía, como si fuera destino.",
"Eres la inspiración detrás de mis mejores sueños.",
"Amarte es mi aventura favorita.",
"Eres el color que le faltaba a mi vida.",
"Tu amor es el viaje más hermoso.",
"Eres mi luna en las noches más oscuras.",
"En cada mirada tuya encuentro un motivo para quedarme.",
"Eres la promesa más dulce de mi vida.",
"Tu corazón es el lugar más hermoso que conozco.",
"Eres mi pensamiento bonito de cada día.",
"Si amar es arte, tú eres mi obra maestra.",
"Eres la dulzura que endulza mi existencia.",
"Tu amor me envuelve como una caricia eterna.",
"Eres el capítulo más bonito de mi historia.",
"Contigo aprendí lo que significa amar de verdad.",
"Eres mi refugio, mi paz, mi amor.",
"Tu ternura derrite hasta el invierno más frío.",
"Eres la estrella que ilumina mi camino.",
"Mi alma te reconoció antes que mis ojos.",
"Eres el amor que siempre esperé.",
"Tu presencia es poesía en movimiento.",
"Eres mi hoy, mi mañana y mi siempre.",
"Amarte es respirar, no puedo dejar de hacerlo.",
"Eres la melodía que mi corazón tararea.",
"Tu amor es mi fortaleza.",
"Eres el sueño hecho realidad.",
"En tus brazos encontré mi lugar en el mundo.",
"Eres la chispa que encendió mi corazón.",
"Tu mirada me dice todo sin palabras.",
"Eres mi amor bonito, mi amor verdadero.",
"Contigo quiero construir todos mis mañanas.",
"Eres la razón por la que creo en el amor.",
"Tu amor es puro, sincero y eterno.",
"Eres mi compañera de alma en esta vida.",
"Si la vida es un viaje, quiero hacerlo contigo.",
"Eres la flor más bella de mi jardín.",
"Tu amor me completa de formas inexplicables.",
"Eres mi sol en días nublados.",
"Amarte es mi decisión más hermosa.",
"Eres la paz que abraza mi corazón.",
"Tu dulzura me enamora cada día más.",
"Eres mi historia favorita para contar.",
"En tu sonrisa habita mi felicidad.",
"Eres el latido que le da ritmo a mi vida.",
"Tu amor es mi mayor tesoro.",
"Eres mi eternidad en un instante.",
"Contigo todo es amor, todo es magia.",
"Eres la persona con la que quiero envejecer.",
"Tu amor me hace sentir en casa.",
"Eres mi deseo hecho realidad.",
"Si el amor fuera un lugar, sería tus brazos.",
"Eres la luz de mis ojos.",
"Tu corazón y el mío laten al mismo ritmo.",
"Eres mi amor, mi vida, mi todo.",
"Amarte es el mejor regalo que me he dado.",
"Eres la prueba de que el amor verdadero existe.",
"Tu ternura es mi debilidad más hermosa.",
"Eres mi cielo en la tierra.",
"Contigo, hasta el silencio es romántico.",
"Eres la musa de mi corazón.",
"Tu amor es infinito como el universo.",
"Eres mi persona favorita en el mundo.",
"Si tuviera una vida, la gastaría amándote.",
"Eres el amor de mi vida.",
"Tu mirada es mi perdición más dulce.",
"Eres mi refugio de amor.",
"Amarte es mi destino.",
"Eres la dulzura de mis días.",
"Tu amor me hace volar sin alas.",
"Eres mi todo y mi nada, mi principio y fin.",
"Contigo quiero escribir nuestra eternidad."
];

let handler = async (m, { conn, usedPrefix, command }) => {
  let who = m.mentionedJid && m.mentionedJid[0]? m.mentionedJid[0] : m.sender;
  let name = '@' + who.split('@')[0];
  let piropo = piropos[Math.floor(Math.random() * piropos.length)];
  let txt = `💌 *Para ${name}*\n\n${piropo}`;
  await conn.sendMessage(m.chat, { text: txt, mentions: [who] }, { quoted: m });
}

handler.help = ['piropo @user'];
handler.tags = ['fun'];
handler.command = ['piropo', 'piropos'];
export default handler;